### ISSUE TITLE
Mobilenet blob mislabled

### ISSUE THREAD

**Issue by Luxonis-Brandon** [luxonis/depthai-docs-website#164]
Running this example:
[https://docs.luxonis.com/projects/api/en/latest/samples/26_1_spatial_mobilenet/](https://docs.luxonis.com/projects/api/en/latest/samples/26_1_spatial_mobilenet/)

When downloading the blob, the file that is downloaded is `mobilenet-ssd_openvino_2021.2_6shave.blob` but the script/example on the docs page is expecting `mobilenet.blob`, resulting in this error after download:

```
Traceback (most recent call last):
  File "261.py", line 60, in <module>
    spatialDetectionNetwork.setBlobPath(nnBlobPath)
RuntimeError: NeuralNetwork node | Blob at path: /Users/leeroy/plgnd/models/mobilenet.blob doesn't exist
```

**Comment by cafemoloko** [comment]
@Luxonis-Brandon, I'll update the docs.

**Comment by Luxonis-Brandon** [comment]
Thanks so I think @szabi-luxonis already did a hotfix.  See internal discussion here: [https://luxonis.slack.com/archives/CTQPP4X33/p1617207146097900?thread_ts=1617205461.095200&cid=CTQPP4X33](https://luxonis.slack.com/archives/CTQPP4X33/p1617207146097900?thread_ts=1617205461.095200&cid=CTQPP4X33)

**Comment by GianniGi** [comment]
still the same problem

D:\sbin\pytorch_DepthAI\depthai-python\depthai-python\examples\ObjectTracker>python spatial_object_tracker.py
Traceback (most recent call last):
  File "D:\sbin\pytorch_DepthAI\depthai-python\depthai-python\examples\ObjectTracker\spatial_object_tracker.py", line 56, in <module>
    spatialDetectionNetwork.setBlobPath(args.nnPath)
RuntimeError: Cannot load blob, file at path D:\sbin\pytorch_DepthAI\depthai-python\depthai-python\examples\models\mobilenet-ssd_openvino_2021.4_5shave.blob doesn't exist.
