### ISSUE TITLE
White background in product photo thumbnail tables

### ISSUE THREAD

**Issue by Luxonis-Brandon** [luxonis/depthai-docs-website#188]
![image](https://user-images.githubusercontent.com/32992551/116894981-ea37f000-abef-11eb-8560-0e626f29b861.png)

**Comment by cafemoloko** [comment]
@Luxonis-Brandon oh I see. Unless we have images without the background, I'll have to edit them by myself (I can do that).

**Comment by Luxonis-Brandon** [comment]
Yes, please edit.  I had to do the others myself.  A bit timeconsuming.  I think there are photoshop-like online tools that are free.

**Comment by cafemoloko** [comment]
> Yes, please edit. I had to do the others myself. A bit timeconsuming. I think there are photoshop-like online tools that are free.

@Luxonis-Brandon I used GIMP to remove background from the rest of the images.

**Comment by Luxonis-Brandon** [comment]
Great - thanks!
