### ISSUE TITLE
Pin-count on OAK-FFC-3P-OG is wrong

### ISSUE THREAD

**Issue by Luxonis-Brandon** [luxonis/depthai-docs-website#256]
The image [here](https://docs.luxonis.com/projects/hardware/en/latest/pages/BW1098FFC.html#board-layout-and-dimensions) shows a 22-pin connector for the left and right cameras, whereas it is actually a 20-pin connector.

![image](https://user-images.githubusercontent.com/32992551/130332321-c8219301-5e80-489c-9fac-13534fa40189.png)

**Comment by Erol444** [comment]
I believe this was already resolved a long time ago, right @Luxonis-David ?

**Comment by Luxonis-David** [comment]
@Erol444 yes it was, I forgot to close the issue with PR.
