### ISSUE TITLE
Add more background on our `myriad_compile` suggested params

### ISSUE THREAD

**Issue by itsderek23** [luxonis/depthai-docs-website#26]
In https://github.com/luxonis/depthai-docs-website/blob/master/_tutorials/openvino_model_zoo_pretrained_model.md#run-myriad_compile, we suggest a number of argument values for `myriad_compile`, but we don't provide background on why.

Provide this information.

**Comment by VanDavv** [comment]
We have a notification in the API that warns the user about the optimal amount of shaves that should be used with a current pipeline to improve performance.
Also, we have a dedicated section about model compiling [here](https://docs.luxonis.com/en/latest/pages/model_conversion/), where we link to official OpenVINO sources the compile commands are mostly network-specific.

However, the tutorial section about `myriad_compile` [here](https://docs.luxonis.com/projects/api/en/latest/tutorials/local_convert_openvino/#run-myriad-compile) would need more description, as mostly there are just code block now

![image](https://user-images.githubusercontent.com/5244214/127324638-e8d235b3-ed6f-42e0-bfbd-64cf50525899.png)

I'll assign myself to this task and circle back with PR that adds some comments on the arguments used
