### ISSUE TITLE
Add information on using the `max_fps`

### ISSUE THREAD

**Issue by itsderek23** [luxonis/depthai-docs-website#30]
https://github.com/luxonis/depthai-python-extras/pull/41 added a `max_fps` setting. Add information on this to https://docs.luxonis.com/api/#depthai_create_pipeline.

**Comment by Luxonis-Brandon** [comment]
Color camera FPS, here: https://docs.luxonis.com/projects/api/en/gen2_develop/references/python/#depthai.ColorCamera
Grayscale cameras, here: https://docs.luxonis.com/projects/api/en/gen2_develop/references/python/#depthai.MonoCamera
