### ISSUE TITLE
request define/clarify `category` and `instanceNum` from `ImgFrame`

### ISSUE THREAD

**Issue by diablodale** [luxonis/depthai-docs-website#301]
I request the docs clarify and add usage information for `category` and `instanceNum` from `ImgFrame`. I see the fields in `RawImgFrame` and there are APIs to get/set them on the ImgFrame. And `examples\host_side\queue_add_callback.cpp` uses the instanceNum.

Here are the topic areas I request be clarified in the documentation

1. `ImgFrame` can be created on device by cameras, NN, scripts, etc. It is unclear what sets the `instanceNum`. Is it set by `dai::CameraBoardSocket`? But then what is `instanceNum` on a depthmap made by `StereoDepth`? Is it the order in which the `config.create<>` call is made? Or order of `->out.link()` to a specific xout from which the `ImgFrame` was get()? 
2. What is `category` and who sets it on the device?
3. Can I declare on the device what the `instanceNum` and `category` should be? For example, I want `instanceNum` for StereoDepth=0 color=1 and pose=2. And even when I don't enable stereodepth...the color will still =1 and pose=2. In this way I can write consistent host-side logic to always process a frame.instancenum=1 as a color frame.
   * Maybe can make a device-side script node and pipe all data into it and (re)set the `instanceNum` and `category` as I want and then xout everything from the script node?
   * Or do I give the desired instanceNum as a parameter to the node's create, node.properties, xout.properties, etc. so all the ImgFrame they process have that specifically declared instancenum?

**Comment by alex-luxonis** [comment]
Thanks, I agree the docs are missing on it, we'll improve. Replying now to the questions:

1. Yes, `instanceNum` is set directly by `dai::CameraBoardSocket`, with this mapping:
```
RGB  (/CAM_A/CENTER) -> 0
LEFT (/CAM_B)        -> 1
RIGHT(/CAM_C)        -> 2
CAM_D                -> 3
```
(different boards will add other socket names as above, we have this in the works)
To make it clearer, I believe we could add an API to return `dai::CameraBoardSocket` instead.

For disparity/depth maps, `instanceNum` is inherited from the source frame where the disparity/depth perspective is mapped to, usually it will be `RIGHT` camera (after rectification). For aligning to RGB, looks like it's not mapped to RGB actually (we'll need to see how to handle).

2. `category` was meant to differentiate between preview/still/etc. types of frames, but seems unused in the firmware at the moment.

3. Not possible now to change / preset  the numbers, but a script node on device could do that, as you mentioned.

**Comment by diablodale** [comment]
got it. I can work with this. :-)

**Comment by diablodale** [comment]
I see unexpected `instanceNum` values when I inspect stereodepth outputs in debug.
`sterodepth.disparity` frames have `instanceNum==1`  🤔
`stereodepth.rectifiedRight` frames has `instanceNum==2`

pseudocode
```c++
auto xoutDisparity = config.create<dai::node::XLinkOut>();
xoutDisparity->setStreamName("disparity");
auto xoutRectRight = config.create<dai::node::XLinkOut>();
xoutRectRight->setStreamName("rectifiedRight");
stereoDepth->disparity.link(xoutDisparity->input);
stereoDepth->rectifiedRight.link(xoutRectRight->input);

stereoDepth->setSubpixel(false);
stereoDepth->setExtendedDisparity(false);
stereoDepth->setRectifyEdgeFillColor(0);
stereoDepth->setDepthAlign(dai::StereoDepthProperties::DepthAlign::RECTIFIED_RIGHT);
stereoDepth->initialConfig.setConfidenceThreshold(255);
stereoDepth->initialConfig.setLeftRightCheckThreshold(5);
stereoDepth->initialConfig.setLeftRightCheck(false);

auto disparity = disparityQueue->tryGet<dai::ImgFrame>()) {
auto rectRight = rectRightQueue->tryGet<dai::ImgFrame>()
```

From your above post, I am expecting `instanceNum == 2` for both. But inspecting the values shows otherwise...
![image](https://user-images.githubusercontent.com/679350/151670005-b643211e-0053-4256-9671-257cfe7a30fe.png)

**Comment by alex-luxonis** [comment]
Thanks! Should be fixed here https://github.com/luxonis/depthai-core/issues/360#issuecomment-1027592213
> Wrong frame instance number for disparity/depth frames, warnings are addressed on https://github.com/luxonis/depthai-core/commit/bb69f2c81cf38685d1ea2a6ca48886a7d6f56a93

**Comment by diablodale** [comment]
good news. with depthai-core `develop` 04d5149e7cfddc4dc871d55d1a3d9ee270b76835
Both the depth and disparity frames from StereoDepth which was aligned to RIGHT perspective shows the expected `instanceNum=2` 
I did not test different perspectives, e.g. LEFT.

I consider the code bug surfaced in this issue resolved. 👍
