### ISSUE TITLE
Update calibration "test depth" step w/new fps_limit

### ISSUE THREAD

**Issue by itsderek23** [luxonis/depthai-docs-website#31]
https://github.com/luxonis/depthai-python-extras/pull/41 added an `fps_limit` option.

Update this step: https://docs.luxonis.com/products/stereo_camera_pair/#test_depth

To use this command:

```
python3 test.py -co '{"streams": [{"name": "depth_sipp", "max_fps": 12.0}]}'
```

**Comment by Luxonis-Brandon** [comment]
Implemented long ago.
