### ISSUE TITLE
Windows Setup with OAK-D Lite

### ISSUE THREAD

**Issue by quitmeyer** [luxonis/depthai-docs-website#313]
I just got the OAK-D Lite, connected it, and went to https://docs.luxonis.com/en/latest/ and then to https://docs.luxonis.com/en/latest/pages/tutorials/first_steps/#first-steps-with-depthai as instructed.

It said for windows to just use the installer.

I run the installer, and then the program automatically runs. It then says "Version 3.0.10 is available. Current version is Unknown Update?"
if I hit "yes" it just brings up this prompt again. If it hit "no" it starts the program. I get a GUI with mostly blank screens
![image](https://user-images.githubusercontent.com/742627/159224151-c432bbc5-024e-4cbd-a6d0-c92dc51e0da2.png)
![image](https://user-images.githubusercontent.com/742627/159224234-b3ec9f18-b078-4f0f-8dd3-8ea818625e29.png)

windows then makes the "device detected"  and then "not detected" sounds a couple times before the program just crashes and quits.
here's the output from the program
![image](https://user-images.githubusercontent.com/742627/159224800-4f4fd584-7a62-49fb-bda7-96797ecb5789.png)

If i physically detach the camera from the computer i get this error when opening the program
![image](https://user-images.githubusercontent.com/742627/159224412-30298788-cbb0-4b81-ad74-299c00414519.png)

**Comment by quitmeyer** [comment]
Note i have tried restarting the computer and plugging into all the different USB ports. The camera also is not detected / doesn't open in amcap (though im not sure if it should)

**Comment by Erol444** [comment]
Hello @quitmeyer ,
We apologize for the inconvenience here. I have noticed that you get USB speed HIGH, which means USB 2. Could you try using a different **USB 3** cable? Often times this resolves the issue you are having.
Thanks, Erik

**Comment by quitmeyer** [comment]
Ahhh, i had figured USB High meant highspeed or USB 3 (but i guess what counts as "HIGH" changes throughout time!) I'll hunt down a different cable this week and report back! thanks!

**Comment by quitmeyer** [comment]
great! found a different cable and got it going. This cable actually still said "HIGH" but it managed to run anyway!
![image](https://user-images.githubusercontent.com/742627/160300178-eb793ee3-3dde-4cca-b4a5-389d87ab3dce.png)
