### ISSUE TITLE
request add details on homography rectification/mesh

### ISSUE THREAD

**Issue by diablodale** [luxonis/depthai-docs-website#316]
Hi. I request the docs increase details on the homography rectification/mesh feature area... to include at least the details surfaced in discord.

```
With the upcoming useHomographyRectification() API, when false ...
What is the mesh step?
Does it use all 14 of the distortion coeffs?
Is it functionally the same as cv::initUndistortRectifyMap()?

[7:37 PM] Luxonis-Szabi: What is the mesh step?
Mesh step is what it's set in config, default 16.
Does it use all 14 of the distortion coeffs?
we use only 8.
Is it functionally the same as cv::initUndistortRectifyMap()? 
yes
loadMeshData overrides useHomographyRectification
```

Could be more to add of which I'm not aware. The above are a good start. 👍

**Comment by szabi-luxonis** [comment]
@diablodale added here: https://github.com/luxonis/depthai-core/commit/35b043d476d5c62ffb21c29225326ff8c8d0ea23

**Comment by diablodale** [comment]
Looking good. Would you please also add:

* uses the first 8 distortion coefficients
* add doc to apis `loadMeshData()` and `loadMeshFiles()`. Some text similar to "use of this api overrides all previous calls to useHomographyRectification()"

**Comment by szabi-luxonis** [comment]
@diablodale Addressed in https://github.com/luxonis/depthai-core/commit/abfbd6ae78f6b9fbee34bf88ecaf4e659bd0976a
Although it was already specified in loadMeshFiles : `When a mesh calibration is set, it overrides the camera intrinsics/extrinsics matrices` , addressing explicitly doesn't hurt.

**Comment by diablodale** [comment]
Thank you. LGTM 👍
