### ISSUE TITLE
Create python virtualenv instructions not shown in docs.luxonis

### ISSUE THREAD

**Issue by RuneSkovrupHansen** [luxonis/depthai-docs-website#345]
Under [Manual DepthAI installation](https://docs.luxonis.com/en/latest/pages/tutorials/manual_installation/#manual-depthai-installation), the commands for the section *(Optional) Create python virtualenv* is not shown on the docs.luxonis page. Looking at the [source .rst file](https://github.com/luxonis/depthai-docs-website/blob/master/source/pages/tutorials/manual_installation.rst) the commands are present, but are just not being shown in the docs.luxonis website.

Visual proof:

![image](https://user-images.githubusercontent.com/73986594/214248650-7ea3c439-dc60-4a4b-b681-62d74bfe8936.png)

Tested using the following browsers:

* https://www.whatsmybrowser.org/b/F30FI
* https://www.whatsmybrowser.org/b/5XISC

**Comment by Erol444** [comment]
Thanks for reporting!
