### ISSUE TITLE
Depth of different objects in the scene

### ISSUE THREAD

**Issue by itsderek23** [luxonis/depthai-docs-website#5]
For example, if a person and a car are detected, determine their distances in meters from the camera.

**Comment by Luxonis-Brandon** [comment]
Initially implemented in Gen1, here: https://github.com/luxonis/depthai-experiments/tree/master/social-distancing

But we need to implement in Gen2, so leaving this open.

**Comment by VanDavv** [comment]
This is implemented in Gen2 here: https://github.com/luxonis/depthai-experiments/tree/master/gen2-social-distancing

I'll close this issue now
