### ISSUE TITLE
Depth seperation between two objects

### ISSUE THREAD

**Issue by itsderek23** [luxonis/depthai-docs-website#7]
For example, if A is 1.5 meters from the camera, and B is 2 meters from the cameras, the depth separation is 0.5 meters.

**Comment by VanDavv** [comment]
This is implemented here - https://github.com/luxonis/depthai-experiments/tree/master/gen2-social-distancing
For tutorials, here are two from [AugmentedStartups](https://www.augmentedstartups.com/) that cover this topic
- https://www.youtube.com/watch?v=xRNFgLuZan8
- https://www.youtube.com/watch?v=6sQVmd2hjgU
